### ISSUE TITLE
Error on getting Map Rotation

### ISSUE THREAD

**Issue by ghost** [JoinedSenses/HelpMenu#1]
Error
```
L 09/09/2021 - 22:34:16: [SM] Exception reported: Invalid index 1 (count: 1)
L 09/09/2021 - 22:34:16: [SM] Blaming: helpmenu.smx
L 09/09/2021 - 22:34:16: [SM] Call stack trace:
L 09/09/2021 - 22:34:16: [SM]   [0] ArrayList.GetString
L 09/09/2021 - 22:34:16: [SM]   [1] Line 246, C:\Users\Arron\Documents\GitHub\HelpMenu\scripting\helpmenu.sp::Help_MainMenuHandler
```

Replace `g_helpMenus` with `g_mapArray` in these two lines to fix it
https://github.com/JoinedSenses/HelpMenu/blob/83eb3602a17b3372f274cc4477dfc5819386f874/scripting/helpmenu.sp#L239
https://github.com/JoinedSenses/HelpMenu/blob/83eb3602a17b3372f274cc4477dfc5819386f874/scripting/helpmenu.sp#L243

I am too lazy to make a pull request

**Comment by JoinedSenses** [comment]
Thanks for the report
