### ISSUE TITLE
Error on reloading config

### ISSUE THREAD

**Issue by ghost** [JoinedSenses/HelpMenu#2]
Error
```
sm_helpmenu_reload
L 09/09/2021 - 23:01:04: [SM] Exception reported: Client index 0 is invalid
L 09/09/2021 - 23:01:04: [SM] Blaming: helpmenu.smx
L 09/09/2021 - 23:01:04: [SM] Call stack trace:
L 09/09/2021 - 23:01:04: [SM]   [0] PrintToChat
L 09/09/2021 - 23:01:04: [SM]   [1] Line 200, C:\Users\Arron\Documents\GitHub\HelpMenu\scripting\helpmenu.sp::Command_HelpMenuReload
```
https://github.com/JoinedSenses/HelpMenu/blob/431508ca96e637cd0e634bd1f5fb347a69c195c8/scripting/helpmenu.sp#L200
Check GetCmdReplySource() to determine what print method should be used so the color codes don't get shown to Console
```
	if (GetCmdReplySource() == SM_REPLY_TO_CHAT) {
		PrintToChat(client, "\x05[SM] \x01Configuration file has been reloaded");
	}
	else {
		ReplyToCommand(client, "[SM] Configuration file has been reloaded");
	}
```
Without check
![image](https://user-images.githubusercontent.com/87161882/132807814-a4ad53b4-1792-41b2-9eeb-7638245a1076.png)

**Comment by JoinedSenses** [comment]
I overlooked your comment about the color code, so I'll modify that now with another commit.

**Comment by JoinedSenses** [comment]
https://github.com/JoinedSenses/HelpMenu/commit/148ea14513a5134bc85d7737ddae5a6c5f89ca3a
